# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "maas4italy-pilot-user-api"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/maas4italy-pilot-user-api"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".gitmodules", ".pre-commit-config.yaml", ".env.example",  "src/go.mod", "src/go.sum"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
