services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://app:8080/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s
    volumes:
      - ${FILEPATH_HOST}:/users.csv
    ports:
      - ${SERVER_PORT}:8080
